name: ppqm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab
  - jupytext
  - matplotlib
  - numpy
  - numpy
  - pandas
  - pip
  - pre-commit
  - pytest
  - pytest-cov
  - scipy
